### ISSUE TITLE
runcython: command not found

### ISSUE THREAD

**Issue by Oussama-dev** [Russell91/runcython#1]
`kaybo@BOST:~$ sudo pip install https://github.com/Russell91/runcython/archive/master.zip`
`[....]`
`Requirement already satisfied (use --upgrade to upgrade): cython in /usr/lib/python2.7/dist-packages ``(from runcython==0.2.3)`
`Cleaning up...`
`kaybo@BOST:~$ runcython test.pyx`
`runcython: command not found`
 I am using Ubuntu 15.04 64bits

**Comment by Russell91** [comment]
Something has gone wrong with your PATH - runcython is no different than any other pip package in this sense. Can you try reinstalling with `sudo pip install runcython -I` (that is a capital i). For example mine is in /usr/local/bin/runcython

**Comment by Oussama-dev** [comment]
Yes that fix the problem, 
and i suggest to remove cython auto installation on pip (as a dependency) when there is a new version installed already, _you know cython new releases may not work properly with some libs like_ __KIVY__.

**Comment by Russell91** [comment]
I didn't know that. Can you suggest a change to https://github.com/Russell91/runcython/blob/master/setup.py that would check for an existing install?

**Comment by Oussama-dev** [comment]
I think it should be automatic :
 _When your project is installed, either by using EasyInstall, setup.py install, or setup.py develop, all of the dependencies_ **not already installed** _will be located (via PyPI), downloaded, built (if necessary), and installed._ 
from http://setuptools.readthedocs.org/en/latest/setuptools.html#declaring-dependencies

but you can always do something crazy like :

```
#!/usr/bin/env python
from setuptools import setup
import os
import sys

depend_on = ''

try:
    import cython                                     # Since the version doesn't mater  
    depend_on = ''                                    # No dependencies 
except:
    depend_on = 'cython'                              # Make Cython as a dependency 


setup(
    name='runcython',
    version='0.2.3',
    description='compile and run cython in one line',
    license='MIT',
    url='https://github.com/Russell91/runcython',
    long_description='https://github.com/Russell91/runcython',
    install_requires= depend_on,         # ---> And Voilà 
    scripts = ['runcython', 'runcython++', 'makecython', 'makecython++'],
)
```

**Comment by Russell91** [comment]
Does pip really have no such mechanism to get these semantics in one line?
And is the alternative that we just drop the cython dependency altogether?

**Comment by Oussama-dev** [comment]
Its supposed to have it (see the link above), but for me it didn't work it reinstall cython every time (maybe the problem is in my pip).
And i don't think you have to do that, i mean no one will use _runcython_ if they don't have _cython_  already.
Nice work by the way its pretty handy.

**Comment by Russell91** [comment]
Yea, I checked this and it seems to behave the way you would like for me. Not sure why you were having trouble, but I'll keep an eye out for other users with the same issue and investigate further if I hear anything. Thanks for the feedback!

**Comment by Oussama-dev** [comment]
You are welcome, and again this is really a great tool.

**Comment by Russell91** [comment]
So I happen to be using setup.py for something else and realized the problem may be that we are not saying install_requires='cython>=0.19' or such. Do you know what version of cython would be a good minimum version to allow?

**Comment by Oussama-dev** [comment]
Not really, but the latest (Cython version 0.22.1) looks great, i didn't had a single problem with it.
