### ISSUE TITLE
OS X: 'pyconfig.h' file not found

### ISSUE THREAD

**Issue by Downchuck** [Russell91/runcython#2]
From a fresh pip install, seems that the include path is not being set, as pkg config python is not setup:

```
✗ runcython use_square.pyx
Package python was not found in the pkg-config search path.
Perhaps you should add the directory containing `python.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python' found
use_square.c:8:10: fatal error: 'pyconfig.h' file not found
#include "pyconfig.h"
```

**Comment by Russell91** [comment]
Please see the memo at the bottom of the readme:

<h4>Configuration for OSX</h4>
python.pc is not on the PKG_CONFIG_PATH by default for OSX. I added
<br/>
`export PKG_CONFIG_PATH=/System/Library/Frameworks/Python.framework/Versions/2.7/lib/pkgconfig`
<br/>
to my ~/.bashrc to solve this.

**Comment by Russell91** [comment]
However, I would like to make a request for comment if anyone has a better way of automatically discovering the python.pc file on popular systems such as OSX (note that Ubuntu doesn't have this issue by default).

**Comment by Downchuck** [comment]
Sorry about that oversight. Also having a struggle on an old (those Hadoop distributors love to stay old) CentOS/Redhat layout.

**Comment by Downchuck** [comment]
Your example of use_square.pyx switches to square.pyx in the escaped shell example.
