### ISSUE TITLE
numpy support?

### ISSUE THREAD

**Issue by brovercleveland** [Russell91/runcython#5]
Hi Russell,

I like your interface for runcython, but is there anyway to include numpy as I would do in vanilla cython, i.e. include_dirs=[numpy.get_include()] in the setup.py file?

**Comment by Russell91** [comment]
Yea, I've actually run into this myself before. The numpy directory needs to be passed with the -I flag to gcc. The best way I've found to deal with this is something like:

    runcython myfile.pyx "" "-I`python -c 'import numpy; print(numpy.get_include())'`"

If things get more complicated than that, you might want to set up a Makefile or bash script where the include directory is precomputed to avoid the nested quotes. This is one area where having a python program setup.py is a little nicer than gcc. But the workaround is straightforward and easy to understand.

**Comment by brovercleveland** [comment]
Thanks, that worked well.
